spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://ajustadoati.com:3307/calch_bk}
    username: ${DATASOURCE_USERNAME:ajustado}
    password: ${DATASOURCE_PASSWORD:Coki447.}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    initialization-mode: always
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 60000
      max-lifetime: 90000
      connection-timeout: 50000

jwt:
  secretKey: vj7/hMQe+EryZ/3V4O8MjT6Vib1FEivj1xwxIZTam4M=

file:
  #dir: /Users/rojasric/projects/files
  dir: /Users/ajustado/caja-ahorro/files

logging:
  level:
    org:
      springframework:
        security: DEBUG
